# Generated by Django 6.0 on 2026-01-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="items",
            field=models.JSONField(),
        ),
    ]
