# Generated by Django 6.0.1 on 2026-01-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_order_stripe_session_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="stripe_session_id",
            field=models.CharField(default="temp-session", max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
