# Generated by Django 5.0.6 on 2026-03-25 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_cartsnapshot_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Product Visibility/Availability'),
        ),
    ]
